### ISSUE TITLE
Chatbot with Monika always freezing the game.

### ISSUE THREAD

**Issue by KitLoaf1** [Rubiksman78/MonikA.I#73]
**Describe the bug**
Whenever I type anything else except "QUIT" the game freezes while Monika is thinking

**To Reproduce**
1. Start Chatbot with Monika
2. Type anything and click enter
3. Game freezes

What am I doing wrong?

**Comment by Rubiksman78** [comment]
This issue with CAI has been fixed with the latest release, please don't forget to login manually with debug mode the first time.

**Comment by KitLoaf1** [comment]
It still crashes when I try to talk to her and The autosubmod updater tells me to update to 1.6.2 how do I update? (I already ran update.bat)

**Comment by Rubiksman78** [comment]
What is displayed with debug mode on? (browser page and terminal outputs if possible).

**Comment by KitLoaf1** [comment]
Nevermind! I guess it works now. It used Microsoft Edge where I haven't logged into c.ai. Everything works now! Thanks!

**Comment by Rubiksman78** [comment]
Good it works ! Closing the issue
